server:
  port: 8080
  servlet:
    context-path: /superApp


spring:
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    url: "jdbc:postgresql://localhost:5432/app-demo-be"
    username: "postgres"
    password: "1234"
    driver-class-name: org.postgresql.Driver

  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
#      jdbc:
#        time_zone: "Asia/Ho_Chi_Minh"
    show-sql: true
    hibernate:
      ddl-auto: update   # hoặc validate, tuỳ nhu cầu
      properties:
        hibernate:
          format_sql: true
      show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9091/realms/SuperApp
  #  cấu hình mail gửi otp
  mail:
    host: smtp.gmail.com
    port: 587
    username: huynhnhutduong7112003@gmail.com # gmail của sender
    password: mval orll zkxu ewim # quản lý tk gg -> xác thực 2 lớp -> app password -> create -> copy + paste pass
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  # cấu hình redis
  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 6000ms
    connect-timeout: 6000ms
  data:
    redis:
      client-type: jedis
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: stock-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
idp:
  url: http://localhost:9091
  client-id: superapp
  client-secret: jdyTm5fi4FBaViekTgWMN0nfBNlPeeSc
keycloak:
  realm: SuperApp
  admin-username: admin
  admin-password: admin123
logging:
  level:
    org.apache.kafka: ERROR
